---

- name: Add license key
  apt_key: id=EA312927 keyserver=hkp://keyserver.ubuntu.com:80 state=present

- name: Create list file for apt
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' state=present

- name: Install Mongo
  apt: name=mongodb-org state=present

- name: Mongod start
  service: name=mongod state=started